//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVRUIModLoader {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CVRUIModLoader.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 /**
        /// * Minified by jsDelivr using UglifyJS v3.3.21.
        /// * Original file: /npm/fetch-polyfill@0.8.2/fetch.js
        /// * 
        /// * Do NOT use SRI with dynamically generated files! More information: https://www.jsdelivr.com/using-sri-with-dynamic-files
        /// */
        ///!function(){&quot;use strict&quot;;if(!self.fetch){h.prototype.append=function(t,e){t=s(t),e=i(e);var r=this.map[t];r||(r=[],this.map[t]=r),r.push(e)},h.prototype.delete=function(t){delete this.map[s(t)]},h.prototype.get=function(t){var e=this.map[s(t)];return e?e[0]:null},h.prototype [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string fetch_min {
            get {
                return ResourceManager.GetString("fetch_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (function () {
        ///
        ///    if(!window[&quot;MUI_LOADED&quot;]){
        ///        window[&quot;MUI_LOADED&quot;]=true;
        ///        loader()
        ///    }
        ///
        ///    async function loader() {
        ///        const MUI_LOADER_ROOT = &quot;coui://uiresources/UIMods/&quot;
        ///
        ///        const ChilloutInjectMap = {
        ///            &quot;coui://uiresources/CVRTest/index.html&quot;: &quot;MainMenu&quot;
        ///        }
        ///
        ///        function loadRemoteJS(url) {
        ///            return new Promise((rs, rj) =&gt; {
        ///                let script = document.createElement(&quot;script&quot;)
        ///                script.src = url
        ///         [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string mui_loader {
            get {
                return ResourceManager.GetString("mui_loader", resourceCulture);
            }
        }
    }
}
